export const CreativeCore = {
    // Генерирует ссылку на изображение по словам
    generateImage: (prompt) => {
        const seed = Math.floor(Math.random() * 1000);
        return `https://pollinations.ai/p/${encodeURIComponent(prompt)}?width=512&height=512&seed=${seed}&model=flux`;
    },
    // Шаблоны генерации кода
    generateCode: (task) => {
        return `// Generated by CyberMind\nfunction quickTask() {\n  console.log("Выполняю: ${task}");\n  // Здесь могла быть ваша логика\n}`;
    }
};
